spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



twilio:
  account_sid: AC644506c37f95e8bf0fe95438abb05047
  auth_token: b5733f266b49cb6fba7f069b44bc6973
<<<<<<< Updated upstream
  trial_number: +15855342449

server:
  port: 8083
=======
  trial_number: +15855342449
>>>>>>> Stashed changes
